esphome:
  name: display_node
  platform: ESP32
  board: esp32dev
  on_boot:
      - output.turn_off: onboard_led

wifi:
  ssid: "Fredrik_AP"
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

spi:
  clk_pin: 13
  mosi_pin: 14

# s= '@!"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz.'
# print([','.join(_) for _ in s])

font:
  - file: 'fonts/Roboto-Bold.ttf'
    id: clock_font
    size: 88
    glyphs: [0, 1, 2, 3, 4, 5, 6, 7 ,8, 9, ':']
  - file: 'fonts/DroidSansMono.ttf'
    id: temp_font
    size: 22
    glyphs:
      ['&', '@', '!', ',', '.', '"', '%', '(', ')', '+', '-', '_', ':', '°', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
       'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
       'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
       'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z','å', 'ä', 'ö', '/']
  - file: 'fonts/DejaVuSansMono-Bold.ttf'
    id: status_font
    size: 14
    glyphs:
      ['&', '@', '!', ',', '.', '"', '%', '(', ')', '+', '-', '_', ':', '°', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
       'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
       'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
       'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z', 'å', 'ä', 'ö', '/']
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: icon_font
    size: 24
    glyphs: [
      '', # mdi-account-heart
      '', # mdi-thermometer
      '󰅢', # mdi-fire-hydrant
      "", # mdi-umbrella
      "ｲ", # mdi-home-thermometer-outline
      "ｱ", # mdi-home-thermometer
      # Wifi
      '冷', # mdi-wifi-strength-outline
      '爛', # mdi-wifi-strength-1
      '嵐', # mdi-wifi-strength-2
      '襤', # mdi-wifi-strength-3
      '蠟', # mdi-wifi-strength-4
      # Weather
      "", # mdi-weather-sunny
      "", # mdi-weather-night
      "", # mdi-weather-cloudy
      "", # mdi-weather-pouring
      "", # mdi-weather-snowy-rainy
      "ｓ", # mdi-weather-snowy-heavy
      "", # mdi-weather-windy-variant
      "", # mdi-weather-fog
      "ｎ", # mdi-weather-night-partly-cloudy
      "", # mdi-weather-partly-cloudy
      # Moon
      "ﾁ", # new_moon
      "ﾄ", # waxing_crecent
      "ｾ", # first_quarter
      "ﾅ", # waxing_gibbous
      "ｿ", # full_moon
      "ﾃ", # waning_gibbous
      "ﾀ", # last_quarter
      "ﾂ", # waning_crescent
      # Sun
      "", # mdi-weather-sunset-down
      "", # mdi-weather-sunset-up
      ]
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: weather_font
    size: 44
    glyphs: [
      '', # mdi-account-heart
      '', # mdi-thermometer
      '󰅢', # mdi-fire-hydrant
      "", # mdi-umbrella
      "ｲ", # mdi-home-thermometer-outline
      # Wifi
      '冷', # mdi-wifi-strength-outline
      '爛', # mdi-wifi-strength-1
      '嵐', # mdi-wifi-strength-2
      '襤', # mdi-wifi-strength-3
      '蠟', # mdi-wifi-strength-4
      # Weather
      "", # mdi-weather-sunny
      "", # mdi-weather-night
      "", # mdi-weather-cloudy
      "", # mdi-weather-pouring
      "", # mdi-weather-snowy-rainy
      "ｓ", # mdi-weather-snowy-heavy
      "", # mdi-weather-windy-variant
      "", # mdi-weather-fog
      "ｎ", # mdi-weather-night-partly-cloudy
      "", # mdi-weather-partly-cloudy
      # Moon
      "ﾁ", # new_moon
      "ﾄ", # waxing_crecent
      "ｾ", # first_quarter
      "ﾅ", # waxing_gibbous
      "ｿ", # full_moon
      "ﾃ", # waning_gibbous
      "ﾀ", # last_quarter
      "ﾂ", # waning_crescent
      ]


display:
  - platform: waveshare_epaper
    id: epaper
    cs_pin: 15
    busy_pin: 25
    reset_pin: 26
    dc_pin: 27
    model: 4.20in
    rotation: 180°
    # full_update_every: 30
    update_interval: 3600s
    lambda: |
      int x, y;
      ESP_LOGI("display", "Updating..");

      /* Print time in HH:MM format */
      it.strftime(125, -10, id(clock_font), TextAlign::TOP_CENTER, "%H:%M", id(current_time).now());

      it.line(259, -10, 259, 200);it.line(261, 0, 261, 200);it.line(260, 0, 260, 200);
      it.line(0, 200, 259, 200);it.line(0, 201, 261, 201);it.line(0, 202, 260, 202);

      it.print(125, 120, id(temp_font), TextAlign::BASELINE_CENTER, "HELLO SUNSHINE!");
      it.print(125, 160, id(icon_font), TextAlign::BASELINE_CENTER, "");
      it.print(125, 182, id(temp_font), TextAlign::BASELINE_CENTER, "Lea & Emma"); // 400 - ((400 - 260)/2)

      /* Moon icon */
      if(id(moon_icon).has_state()) {
        y = 260, x = 240;
        ESP_LOGI("Moon icon", "%s", id(moon_icon).state.c_str());
        it.printf(x, y, id(weather_font), TextAlign::BASELINE_CENTER, "%s", id(moon_icon).state.c_str());
      }
      /* WiFi Signal Strenght */
      if(id(wifisignal).has_state()) {
        x = 398, y = 298;
        if (id(wifisignal).state >= -50) {
            //Excellent
            it.print(x, y, id(icon_font), TextAlign::BOTTOM_RIGHT, "蠟");
            ESP_LOGI("WiFi", "Exellent");
        } else if (id(wifisignal).state  >= -60) {
            //Good
            it.print(x, y, id(icon_font), TextAlign::BOTTOM_RIGHT, "襤");
            ESP_LOGI("WiFi", "Good");
        } else if (id(wifisignal).state  >= -67) {
            //Fair
            it.print(x, y, id(icon_font), TextAlign::BOTTOM_RIGHT, "嵐");
            ESP_LOGI("WiFi", "Fair");
        } else if (id(wifisignal).state  >= -70) {
            //Weak
            it.print(x, y, id(icon_font), TextAlign::BOTTOM_RIGHT, "爛");
            ESP_LOGI("WiFi", "Weak");
        } else {
            //Unlikely working signal
            it.print(x, y, id(icon_font), TextAlign::BOTTOM_RIGHT, "冷");
            ESP_LOGI("WiFi", "Unlikely");
        }
      }

      // Current weather
      if(id(weather_forecast_today).has_state()) {
        std::string str = id(weather_forecast_today).state;
        ESP_LOGI("Weather", "%s", str.c_str());
        std::size_t current, previous = 0;
        char delim = ';';
        current = str.find(delim);
        int y = 250, x = 5;
        for (int i=0; i<3; i++) {
            if(i == 0) {
              it.printf(x, y, id(weather_font),
                TextAlign::BASELINE_LEFT,
                "%s", str.substr(previous, current - previous).c_str());
            } else if (i == 1) {
              ESP_LOGD("weather","%dx%d %s", (i % 1 ? 270 : 320), x,
                str.substr(previous, current - previous).c_str());
              /* it.printf(y, x, id(status_font),
                TextAlign::TOP_LEFT,
                "%s", str.substr(previous, current - previous).c_str());
              */
            } else if (i == 2) { // Chance for rain
              it.printf(x, y + 2, id(icon_font), TextAlign::TOP_LEFT, "");
              it.printf(x + 25, y + 8, id(status_font),
                TextAlign::TOP_LEFT,
                "%s %%", str.substr(previous, current - previous).c_str());
            }
            // y += 100;
            previous = current + 1;
            current = str.find(delim, previous);
        }
      }

      // Print inside temperature (from homeassistant sensor)
      y = 245, x = 90;
      if (id(inside_temperature).has_state()) {
        it.print(x, y, id(icon_font), TextAlign::BOTTOM_RIGHT, "ｱ");
        it.printf(x, y, id(temp_font), TextAlign::BOTTOM_LEFT , "% 3.1f°", id(inside_temperature).state);
      }
      // Print outside temperature (from homeassistant sensor)
      if (id(outside_temperature).has_state()) {
        it.print(x, y, id(icon_font), TextAlign::TOP_RIGHT, "ｲ"); 
        it.printf(x, y, id(temp_font), TextAlign::TOP_LEFT, "% 3.1f°", id(outside_temperature).state);
      }

      // Print consumer
      if (id(top_consumer).has_state()) {
        it.printf(0, 295, id(status_font), TextAlign::BOTTOM_LEFT , "Total: %.0f W, top user: %s W", id(sparsnas).state, id(top_consumer).state.c_str());

      }
      // it.line(0, 299, 400, 299);

      // std::string str = "mon:cloud:12.1:30%:tue:rain:10.2:40%:wed:sunny:18.0:0%:thu:snow:-12.2:10%";
      if(id(weather_forecast).has_state()) {
        std::string str = id(weather_forecast).state;
        ESP_LOGI("Weather", "%s", str.c_str());
        std::size_t current, previous = 0;
        char delim = ';';
        current = str.find(delim);
        int x = 340, y = 5;
        for (int i=0; i<4; i++) {
          ESP_LOGI("t", "%d", i);
          for (int j=0; j<4; j++) {
            if(j == 1) {
              it.printf(x - 60, y + 28, id(weather_font),
                TextAlign::BASELINE_LEFT,
                "%s", str.substr(previous, current - previous).c_str());
            } else {
              ESP_LOGD("weather","%dx%d %s", (j % 1 ? 270 : 320), x,
                str.substr(previous, current - previous).c_str());
              it.printf((j == 0 ? x - 10 : 390), y,
                id(status_font),
                (j == 0 ? TextAlign::TOP_LEFT : TextAlign::TOP_RIGHT),
                "%s", str.substr(previous, current - previous).c_str());
              y += 13;
            }
            previous = current + 1;
            current = str.find(delim, previous);
          }
          y += 8;
        }
      }
output:
  - platform: gpio
    id: onboard_led
    pin:
      number: 2
      inverted: False

light:
  - platform: binary
    name: "Onboard LED"
    output: onboard_led

time:
  - platform: homeassistant
    id: current_time
    timezone: Europe/Stockholm
    on_time:
      # Every 1 minutes
      - seconds: 0
        then:
          - component.update: epaper


sensor:
  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.vit_inne_temperature
    internal: true

  - platform: homeassistant
    id: outside_temperature
    entity_id: sensor.ute_temperature
    internal: true

  - platform: homeassistant
    entity_id: sensor.sparsnas_energy_consumption_momentary
    id: sparsnas
    internal: true

  - platform: homeassistant
    entity_id: sensor.dark_sky_precip_probability
    id: precip_probability
    internal: true

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    id: wifisignal
    update_interval: 60s

text_sensor:
  - platform: homeassistant
    id: top_consumer
    entity_id: sensor.iotawatt_top_consumer
    internal: true

  - platform: homeassistant
    name: forecast
    id: weather_forecast
    entity_id: sensor.forecast
    internal: true

  - platform: homeassistant
    name: forecast
    id: weather_forecast_today
    entity_id: sensor.forecast_today
    internal: true

  - platform: homeassistant
    id: moon_icon
    entity_id: sensor.moon_tpl

