esphome:
  name: led_strip
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "Fredrik_AP"
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

light:
  - platform: fastled_clockless
    chipset: NEOPIXEL
    pin: D3
    num_leds: 100
    name: "LED strip"
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50
      - addressable_color_wipe:
      - addressable_scan:
          name: Scan Effect With Custom Values
          move_interval: 200ms
      - addressable_fireworks:
      - addressable_twinkle:
          name: Twinkle Effect With Custom Values
          twinkle_probability: 5%
          progress_interval: 4ms
